api/urls.py
from django.urls import path

from api.views import AssistanceViewSet

app_name = "api"

urlpatterns = [
    path("assistance/", AssistanceViewSet.as_view({"get": "list"})),
    path("assistance/detail/<int:pk>/", AssistanceViewSet.as_view({"get": "retrieve"}))
]

assistance/urls.py
from django.urls import path

from assistance import views

app_name = "assistance"

urlpatterns = [
    path("", views.AssistanceListView.as_view(), name="assistance-list"),
    path("create/", views.AssistanceCreateView.as_view(), name="assistance-create"),
    path("detail/<int:pk>/", views.AssistanceDetailView.as_view(), name="assistance-detail"),
    path("update/<int:pk>/", views.AssistanceUpdateView.as_view(), name="assistance-update"),
    path("delete/<int:pk>/", views.AssistanceDeleteView.as_view(), name="assistance-delete")
]

authentication/urls.py
from django.urls import path

from authentication import views

app_name = "authentication"

urlpatterns = [
    path("sign_up/", views.RegisterView.as_view(), name="sign_up"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password_reset/", views.ResetPasswordView.as_view(), name="password-reset"),
    path(
        "password_reset/done/",
        views.ResetPasswordDoneView.as_view(),
        name="password-reset-done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.ResetPasswordConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "reset/done/",
        views.ChangePasswordCompleteView.as_view(),
        name="password-reset-complete",
    )
]

portal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from graphene_django.views import GraphQLView
from rest_framework_swagger.views import get_swagger_view

from api.schemas import schema
from portal import settings

schema_view = get_swagger_view(title='Volunteer portal API')

urlpatterns = [
    path('admin/', admin.site.urls),

    path("auth/", include("authentication.urls")),
    path("auth/", include("social_django.urls"), name="social"),
    path("profile/", include("user_profile.urls")),
    path("follower/", include("follower.urls")),
    path("user/", include("user.urls")),
    path("assitance/", include("assistance.urls")),
    path("petition/", include("petition.urls")),

    path("api/", include("api.urls")),
    path("swagger/", schema_view),

    path("graphql/", GraphQLView.as_view(graphiql=True, schema=schema)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from user import views

app_name = "user"

urlpatterns = [
    path("", views.UserListView.as_view(), name="user-list"),
    path("detail/<int:pk>/", views.UserDetailView.as_view(), name="user-detail")
]

user_profile/forms.py
from django import forms

from authentication.models import User


class UserForm(forms.ModelForm):
    user_photo = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ["user_photo", "email", "first_name", "last_name", "birth_date", "bio"]

user_profile/views/verify.py
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.views import View

from authentication.models import User
from user_profile.services.utils import generate_token
from user_profile.tasks import send_verify_email


class VerifyUser(View):
    def post(self, request, *args, **kwargs):
        send_verify_email(user=request.user, request=request)
        return reverse_lazy("user_profile:profile")


def verify_user(uidb64, token):
    uid = str(urlsafe_base64_decode(uidb64))
    user = User.objects.get(pk=uid)

    if user and generate_token.check_token(user, token):
        user.is_verified = True
        user.save()

        return reverse_lazy('user_profile:profile')

templates/user_profile/base.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

templates/user_profile/base_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="border-2 rounded-lg flex mt-6 ml-6">
        <aside class="w-72" aria-label="Sidebar">
            <div class="overflow-y-auto rounded-tl-lg rounded-bl-lg py-4 h-full px-3 bg-gray-100">
                <ul class="space-y-2">
                    <li>
                        <a href="{% url 'user_profile:profile-update' %}"
                           class="flex items-center p-2 text-base {% block active_edit_profile_item %}{% endblock active_edit_profile_item %} text-gray-900 rounded-lg dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700">
                            <span class="flex-1 ml-3 whitespace-nowrap">Edit profile</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'user_profile:password-change' %}"
                           class="flex items-center p-2 text-base {% block active_change_password_item %}{% endblock active_change_password_item %} text-gray-900 rounded-lg dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700">
                            <span class="flex-1 ml-3 whitespace-nowrap">Change password</span>
                        </a>
                    </li>
                    <li>
                        <a class="flex items-center p-2 text-base {% block active_logout_item %}{% endblock active_logout_item %} font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700" type="button" data-modal-toggle="logout-modal">
                            <span class="flex-1 ml-3 whitespace-nowrap">Log Out</span>
                        </a>
                    </li>
                </ul>
            </div>
        </aside>
        {% block edit %}{% endblock edit %}
    </div>
{% endblock content %}

templates/user_profile/password_change_form.html
{% extends 'user_profile/base_update.html' %}

{% block active_change_password_item %}font-medium{% endblock active_change_password_item %}

{% block edit %}
    <div style="width: 80%;"
         class="w-max m-auto w-2/4 rounded-r-lg p-4 bg-white">
        <form method="post">
            {% csrf_token %}
            <div>
                <div>
                    <label for="old_password" class="block text-base font-medium">Old password</label>
                    <input type="password" name="old_password" id="old_password" placeholder="••••••••"
                           class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-1/2 p-2">
                </div>
                <div class="mt-2">
                    <label for="new_password" class="block text-base font-medium">New password</label>
                    <input type="password" name="new_password1" id="new_password" placeholder="••••••••"
                           class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-1/2 p-2">
                </div>
                <div class="mt-2">
                    <label for="confirm_new_password" class="block text-base font-medium">Confirm new password</label>
                    <input type="password" name="new_password2" id="confirm_new_password" placeholder="••••••••"
                           class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-1/2 p-2">
                </div>
            </div>
            <div class="mt-4 flex justify-start">
                <button type="submit"
                        class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                    Change Password
                </button>
                <a href="{% url 'authentication:password-reset' %}" class="flex items-center ml-6 text-sm text-blue-500 font-medium">Forgot Password?</a>
            </div>
        </form>
    </div>
{% endblock edit %}

templates/user_profile/profile.html
{% extends 'user_profile/base.html' %}

{% block content %}
<div class="flex p-5">
    <div>
        <img class="w-36 h-36 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-5.jpg"
            alt="Rounded avatar" />
    </div>
    <div>
        <div class="flex ml-6 mt-4">
            <div class="ml-1 mr-8">
                <h3 class="text-xl font-medium items-center" style="text-transform: capitalize">
                    {{ user.first_name }} {{ user.last_name }}
                </h3>
            </div>
            <div class="ml-6 mr-0">
                <a class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-4 py-2 text-center mr-2"
                    href="{% url 'user_profile:profile-update' %}">Edit Profile</a>
                <a class="text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-full text-sm px-4 py-2 text-center"
                    href="{% url 'user:user-detail' user.id %}">Public View</a>
            </div>
        </div>
        <div class="flex ml-6 mt-4 text-sm">
            <div class="flex ml-1 mr-4">
                <p class="font-bold">{{ assistance_count }}</p>
                <p class="ml-1">assistance</p>
            </div>
            <div class="flex mr-4">
                <p class="font-bold">{{ follower_count }}</p>
                <p class="ml-1">followers</p>
            </div>
            <div class="flex">
                <p class="font-bold">{{ following_count }}</p>
                <p class="ml-1">following</p>
            </div>
        </div>
        <div class="ml-6 mt-4">
            <div style="width: 28rem;" class="ml-1">
                <p class="text-sm">{{ user.bio|default:"" }}</p>
            </div>
        </div>
    </div>
</div>
<div
    class="text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
    <ul class="flex justify-between">
        <li class="mr-2">
            <a
                class="inline-block p-3 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active">Assistance</a>
        </li>
        <li class="mr-2 flex items-center">
            <a href="{% url 'assistance:assistance-create' %}" class="inline-block text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-1.5 text-center">
                Add Assistance
            </a>
        </li>
    </ul>
</div>

<div class="mt-2 grid grid-cols-2 gap-2 pb-2">
    {% for item in assistance %}
    <div class="w-full bg-white rounded-lg border border-gray-200 shadow-md">
        <div class="flex justify-end px-4 pt-3 pb-2 relative">
            <button id="dropdownButton" data-dropdown-toggle="dropdown"
                class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg text-sm p-1.5"
                type="button">
                <span class="sr-only">Open dropdown</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z">
                    </path>
                </svg>
            </button>
            <!-- Dropdown menu -->
            <div id="dropdown"
                class="hidden z-10 w-44 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700">
                <ul class="py-1" aria-labelledby="dropdownButton">
                    {% if item.user == request.user %}
                    <li>
                        <a href="{% url 'assistance:assistance-update' item.id %}"
                            class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100">Edit</a>
                    </li>
                    <li>
                        <a href="{% url 'assistance:assistance-delete' item.id %}"
                            class="block py-2 px-4 text-sm text-red-600 hover:bg-gray-100">Delete</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="#"
                            class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100">Report</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="w-f bg-white rounded-lg">
            <a href="{% url 'assistance:assistance-detail' item.id %}">
                <img class="px-5" src="https://flowbite.com/docs/images/blog/image-1.jpg" alt="" />
            </a>
            <div class="p-5">
                <a>
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">
                        {{ item.name }}
                    </h5>
                </a>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                    {{ item.description|truncatechars_html:110 }}
                </p>
                <a href="{{ item.payment_url }}" target="_blank"
                    class="inline-flex items-center focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900">
                    Donate
                </a>
                <a href="{% url 'assistance:assistance-detail' item.id %}"
                    class="inline-flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
                    Detail
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/user_profile/profile_update_form.html
{% extends 'user_profile/base_update.html' %}

{% block active_edit_profile_item %}font-medium{% endblock active_edit_profile_item %}

{% block edit %}
    <div style="width: 80%;"
         class="w-max m-auto w-2/4 rounded-r-lg p-4 bg-white">
        <form method="post">
            {% csrf_token %}
            <div>
                <div>
                    {% if user.user_photo %}
                        <img id="avatar" class="w-10 h-10 rounded-full"
                             src="{{ user.user_photo.url }}"
                             alt="user photo">
                    {% else %}
                        <img id="avatar" class="w-10 h-10 rounded-full"
                         src="https://flowbite.com/docs/images/people/profile-picture-5.jpg"
                         alt="user photo">
                    {% endif %}
                    <label class="text-sm font-medium text-blue-600" for="photo">Change profile photo</label>
                    <input type="file" value="{{ user.user_photo }}" accept=".png, .jpeg, .jpg" name="user_photo"
                           id="photo" style="display: none"
                           onchange="document.getElementById('avatar').src = window.URL.createObjectURL(this.files[0])">
                </div>
                <div class="mt-2 grid md:grid-cols-2 md:gap-6">
                    <div>
                        <label for="first_name" class="block text-base font-medium text-gray-900">First
                            name</label>
                        <input type="text" name="first_name" id="first_name" placeholder="Joe"
                               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2"
                               value="{{ user.first_name }}">
                    </div>
                    <div class="">
                        <label for="last_name" class="block text-base font-medium text-gray-900">Last
                            name</label>
                        <input type="text" name="last_name" id="last_name" placeholder="Doe"
                               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2"
                               value="{{ user.last_name }}">
                    </div>
                </div>
                <div class="mt-2 grid md:grid-cols-2 md:gap-6">
                    <div>
                        <label for="email" class="block text-base font-medium text-gray-900">Email</label>
                        <input type="email" name="email" id="email"
                               class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2"
                               placeholder="email@gmail.com" value="{{ user.email }}">
                    </div>
                    <div>
                        <label for="date_of_birth" class="block text-base font-medium text-gray-900 dark:text-gray-300">Date
                            of birth</label>
                        <div class="relative">
                            <div class="flex absolute left-0 items-center pl-3 pointer-events-none" style="top: 24%;">
                                <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400"
                                     fill="currentColor"
                                     viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                          d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
                                          clip-rule="evenodd"></path>
                                </svg>
                            </div>
                            <input datepicker name="birth_date" id="date_of_birth" type="text"
                                   class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2"
                                   placeholder="Select date" value="{{ user.birth_date }}">
                        </div>
                    </div>
                </div>
                <div class="mt-2">
                    <label for="bio" class="block text-base font-medium text-gray-900 dark:text-gray-400">Bio</label>
                    <textarea id="bio" name="bio" rows="4" style="resize: none;"
                              class="block p-2 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500">{% if user.bio is None %}{% else %}{{ user.bio }}{% endif %}</textarea>
                </div>
            </div>
            <div class="mt-4 flex justify-start">
                <button type="submit"
                        class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
                    Submit
                </button>
            </div>
        </form>
    </div>
{% endblock edit %}