api/urls.py
from django.urls import path

from api.views import AssistanceViewSet

app_name = "api"

urlpatterns = [
    path("assistance/", AssistanceViewSet.as_view({"get": "list"})),
    path("assistance/detail/<int:pk>/", AssistanceViewSet.as_view({"get": "retrieve"}))
]

authentication/urls.py
from django.urls import path

from authentication import views

app_name = "authentication"

urlpatterns = [
    path("sign_up/", views.RegisterView.as_view(), name="sign_up"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password_reset/", views.ResetPasswordView.as_view(), name="password-reset"),
    path(
        "password_reset/done/",
        views.ResetPasswordDoneView.as_view(),
        name="password-reset-done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.ResetPasswordConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "reset/done/",
        views.ChangePasswordCompleteView.as_view(),
        name="password-reset-complete",
    )
]

portal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from graphene_django.views import GraphQLView
from rest_framework_swagger.views import get_swagger_view

from api.schemas import schema
from portal import settings

schema_view = get_swagger_view(title='Volunteer portal API')

urlpatterns = [
    path('admin/', admin.site.urls),

    path("auth/", include("authentication.urls")),
    path("auth/", include("social_django.urls"), name="social"),
    path("profile/", include("user_profile.urls")),
    path("follower/", include("follower.urls")),
    path("user/", include("user.urls")),
    path("assitance/", include("assistance.urls")),
    path("petition/", include("petition.urls")),

    path("api/", include("api.urls")),
    path("swagger/", schema_view),

    path("graphql/", GraphQLView.as_view(graphiql=True, schema=schema)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authentication/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from django.db import models

from authentication.managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name="email", max_length=250, unique=True)
    first_name = models.CharField(verbose_name="first name", max_length=40)
    last_name = models.CharField(verbose_name="last name", max_length=80)
    birth_date = models.DateField(verbose_name="birth date", null=True)
    user_photo = models.ImageField(verbose_name="user photo", upload_to="users/", blank=True, null=True)
    bio = models.TextField(verbose_name="bio", max_length=150, blank=True, null=True)
    is_active = models.BooleanField(verbose_name="is active", default=True)
    is_superuser = models.BooleanField(verbose_name="is superuser", default=False)
    is_verified = models.BooleanField(verbose_name="is verified", default=False)
    is_staff = models.BooleanField(verbose_name="is staff", default=False)

    USERNAME_FIELD = "email"

    objects = UserManager()

    def __str__(self):
        return f'{self.id}, {self.email}'

    class Meta:
        db_table = "users"
        ordering = ("-id",)

    @property
    def full_name(self):
        username = (
            self.first_name + " " + self.last_name
            if self.first_name and self.last_name else self.email
        )
        return username

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm

from authentication.models import User


class UserRegisterForm(UserCreationForm):
    """Custom UserCreationForm"""

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
            "birth_date",
            "password1",
            "password2"
        ]

authentication/views.py
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,\
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.contrib.auth import logout

from authentication.forms import UserRegisterForm


class RegisterView(CreateView):
    template_name = 'authentication/sign_up.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy("authentication:login")

    def form_valid(self, form):
        form.save()

        user = authenticate(
            email=form.cleaned_data.get('email'),
            password=form.cleaned_data.get('password1')
        )

        if user is not None:
            login(self.request, user)
            messages.success(self.request, "Login successful")
        else:
            messages.error(self.request, "Cannot login")

        return super().form_valid(form)


class CustomLoginView(LoginView):
    template_name = 'authentication/login.html'


class CustomLogoutView(LogoutView):
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return reverse_lazy("authentication:login")


class ResetPasswordView(PasswordResetView):
    template_name = "authentication/password_reset_form.html"
    subject_template_name = "email/password_reset_subject.txt"
    email_template_name = "email/password_reset_email.html"
    success_url = reverse_lazy("authentication:password-reset-done")


class ResetPasswordDoneView(PasswordResetDoneView):
    template_name = "message/password_reset_done.html"


class ResetPasswordConfirmView(PasswordResetConfirmView):
    template_name = "authentication/password_reset_confirm.html"
    success_url = reverse_lazy("authentication:password-reset-complete")


class ChangePasswordCompleteView(PasswordResetCompleteView):
    template_name = "message/password_reset_complete.html"

templates/authentication/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/flowbite.min.css" %}">
</head>
<body>
    <div class="m-0 p-0 h-screen flex justify-center items-center">
        {% block form %}{% endblock %}
    </div>
    <script src="{% static "js/flowbite.js" %}"></script>
    <script src="{% static "js/datepicker.js" %}"></script>
</body>
</html>

templates/authentication/login.html
{% extends 'authentication/base.html' %}

{% block title %}Login{% endblock %}

{% block form %}
    <div class="relative top-0 bottom-0 left-0 right-0 m-auto p-4 w-full max-w-sm bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 md:p-8">
        <form class="space-y-6" method="post">
            {% csrf_token %}
            <h5 class="text-xl text-center font-bold text-gray-900 dark:text-white">Login</h5>
            <div>
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your
                    email</label>
                <input type="email" name="username" id="email"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                       placeholder="name@company.com" value="{{ form.data.email }}">
            </div>
            <div>
                <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your
                    password</label>
                <input type="password" name="password" id="password" placeholder="••••••••"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                       value="{{ form.data.password }}">
            </div>
            <div class="flex items-start">
                <div class="flex items-start">
                    <div class="flex items-center h-5">
                        <input id="remember" type="checkbox" value=""
                               class="w-4 h-4 bg-gray-50 rounded border border-gray-300 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800"
                               required="">
                    </div>
                    <label for="remember" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Remember
                        me</label>
                </div>
                <a href="{% url 'authentication:password-reset' %}"
                   class="ml-auto text-sm text-blue-700 hover:underline dark:text-blue-500">Forgot Password?</a>
            </div>
            <button type="submit"
                    class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Login to your account
            </button>
            <div class="text-sm font-medium text-gray-500 dark:text-gray-300">
                Not registered? <a href="{% url 'authentication:sign_up' %}"
                                   class="text-blue-700 hover:underline dark:text-blue-500">Create account</a>
            </div>

            <div class="block">
                <p class="text-center font-medium mx-4 mb-0">OR</p>
            </div>
            <div class="flex justify-between">

                <a class="px-6 py-2 text-white font-medium text-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out min-w-max flex justify-center w-1/2 items-center mr-2"
                   href="#!">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="rgb(107 114 128)"
                         class="bi bi-facebook" viewBox="0 0 16 16">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                    </svg>
                </a>
                <a class="px-6 py-2 text-white font-medium text-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 focus:shadow-lg focus:outline-none focus:ring-0 active:shadow-lg transition duration-150 ease-in-out min-w-max flex justify-center w-1/2 items-center" href="#!">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="rgb(107 114 128)"
                         class="bi bi-google" viewBox="0 0 16 16">
                        <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z"/>
                    </svg>
                </a>
            </div>
        </form>
    </div>
{% endblock %}

templates/authentication/password_reset_confirm.html
{% extends 'authentication/base.html' %}

{% block title %}Set password{% endblock %}

{% block form %}
    <div class="relative top-0 bottom-0 left-0 right-0 m-auto p-4 w-full max-w-sm bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
        <h2 class="mb-1 text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
            Set Password
        </h2>
        <form class="mt-4 space-y-4 lg:mt-5 md:space-y-5" action="#">
            <div>
              <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">New Password</label>
              <input type="password" name="new_password1" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
            </div>
            <div>
              <label for="confirm-password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirm password</label>
              <input type="confirm-password" name="new_password2" id="confirm-password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required="">
            </div>
            <div class="flex items-start">
              <div class="flex items-center h-5">
                <input id="newsletter" aria-describedby="newsletter" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800" required="">
              </div>
              <div class="ml-3 text-sm">
                <label for="newsletter" class="font-light text-gray-500 dark:text-gray-300">I accept the <a class="font-medium text-primary-600 hover:underline dark:text-primary-500" href="#">Terms and Conditions</a></label>
              </div>
            </div>
            <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Reset password</button>
        </form>
    </div>
{% endblock %}

templates/authentication/password_reset_form.html
{% extends 'authentication/base.html' %}

{% block title %}Reset password{% endblock %}

{% block form %}
    <div class="relative top-0 bottom-0 left-0 right-0 m-auto p-4 w-full max-w-sm bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 md:p-8">
        <form class="space-y-3" method="POST">
        {% csrf_token %}
        <h5 class="text-xl text-center font-medium mt-0 text-gray-900 dark:text-white">Forgot password</h5>
        <div>
            <label for="id_email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Email</label>
            <input type="email" name="email" id="email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" placeholder="email@gmail.com" required="" value="{{ request.user.email }}">
        </div>
        <button class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Reset password</button>
    </form>
    </div>
{% endblock %}

templates/authentication/sign_up.html
{% extends 'authentication/base.html' %}

{% block title %}Sign up{% endblock %}

{% block form %}
    <div class="relative top-0 bottom-0 left-0 right-0 m-auto p-4 w-full max-w-md bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
        <form class="space-y-6" method="post">
            {% csrf_token %}
            <h5 class="text-xl text-center font-bold text-gray-900 dark:text-white">Sign up</h5>
            <div class="grid md:grid-cols-2 md:gap-6">
                <div>
                    <label for="first_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">First
                        name</label>
                    <input type="text" name="first_name" id="first_name" placeholder="Joe"
                           class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                           required="" value="{{ form.data.first_name }}">
                </div>
                <div>
                    <label for="last_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Last
                        name</label>
                    <input type="text" name="last_name" id="last_name" placeholder="Doe"
                           class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                           required="" value="{{ form.data.last_name }}">
                </div>
            </div>
            <div>
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Email</label>
                <input type="email" name="email" id="email"
                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                       placeholder="email@gmail.com" required="" value="{{ form.data.email }}">
            </div>
            <div class="relative">
                <label for="date_of_birth" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Date
                    of birth</label>
                <div>
                    <div class="flex absolute left-0 items-center pl-3 pointer-events-none" style="top: 55%;">
                        <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor"
                             viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                  d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z"
                                  clip-rule="evenodd"></path>
                        </svg>
                    </div>
                    <input datepicker name="birth_date" id="date_of_birth" type="text"
                           class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                           placeholder="Select date" value="{{ form.data.birth_date }}">
                </div>
            </div>
            <div class="grid md:grid-cols-2 md:gap-6">
                <div>
                    <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Password</label>
                    <input type="password" name="password1" id="password" placeholder="••••••••"
                           class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                           required="" value="{{ form.data.password1 }}">
                </div>
                <div>
                    <label for="confirm_password"
                           class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Confirm
                        password</label>
                    <input type="password" name="password2" id="confirm_password" placeholder="••••••••"
                           class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                           required="" value="{{ form.data.password2 }}">
                </div>
            </div>
            <button type="submit"
                    class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Create an account
            </button>
            <div class="text-sm font-medium text-gray-500 dark:text-gray-300">
                Already have an account? <a href="{% url 'authentication:login' %}"
                                            class="text-blue-700 hover:underline dark:text-blue-500">Login</a>
            </div>
        </form>
    </div>
{% endblock %}