api/urls.py
from django.urls import path

from api.views import AssistanceViewSet

app_name = "api"

urlpatterns = [
    path("assistance/", AssistanceViewSet.as_view({"get": "list"})),
    path("assistance/detail/<int:pk>/", AssistanceViewSet.as_view({"get": "retrieve"}))
]

assistance/urls.py
from django.urls import path

from assistance import views

app_name = "assistance"

urlpatterns = [
    path("", views.AssistanceListView.as_view(), name="assistance-list"),
    path("create/", views.AssistanceCreateView.as_view(), name="assistance-create"),
    path("detail/<int:pk>/", views.AssistanceDetailView.as_view(), name="assistance-detail"),
    path("update/<int:pk>/", views.AssistanceUpdateView.as_view(), name="assistance-update"),
    path("delete/<int:pk>/", views.AssistanceDeleteView.as_view(), name="assistance-delete")
]

petition/urls.py
from django.urls import path

from petition import views

app_name = "petition"

urlpatterns = [
    path("", views.PetitionListView.as_view(), name="petition-list"),
    path("detail/<int:pk>/", views.PetitionDetailView.as_view(), name="petition-detail")
]

portal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from graphene_django.views import GraphQLView
from rest_framework_swagger.views import get_swagger_view

from api.schemas import schema
from portal import settings

schema_view = get_swagger_view(title='Volunteer portal API')

urlpatterns = [
    path('admin/', admin.site.urls),

    path("auth/", include("authentication.urls")),
    path("auth/", include("social_django.urls"), name="social"),
    path("profile/", include("user_profile.urls")),
    path("follower/", include("follower.urls")),
    path("user/", include("user.urls")),
    path("assitance/", include("assistance.urls")),
    path("petition/", include("petition.urls")),

    path("api/", include("api.urls")),
    path("swagger/", schema_view),

    path("graphql/", GraphQLView.as_view(graphiql=True, schema=schema)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from user import views

app_name = "user"

urlpatterns = [
    path("", views.UserListView.as_view(), name="user-list"),
    path("detail/<int:pk>/", views.UserDetailView.as_view(), name="user-detail")
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <base href="../">

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/flowbite.min.css" %}">
</head>
<body class="m-0 p-0 h-screen">

<nav class="bg-white border-solid border-b-2 border-b-gray-600 px-2 sm:px-4 py-2.5">
    <div class="container flex flex-wrap justify-between items-center mx-auto">
        <a href="https://flowbite.com/" class="flex items-center">
            <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo">
            <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
        </a>
        <div class="flex items-center md:order-2">
            <button type="button"
                    class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
                    id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown"
                    data-dropdown-placement="bottom">
                <span class="sr-only">Open user menu</span>
                <img class="w-8 h-8 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-5.jpg"
                     alt="user photo">
            </button>
            <!-- Dropdown menu -->
            <div class="z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 hidden"
                 id="user-dropdown" data-popper-reference-hidden="" data-popper-escaped=""
                 data-popper-placement="bottom"
                 style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(599.5px, 91px, 0px);">
                <div class="py-3 px-4">
                    <span class="block text-sm text-gray-900 dark:text-white">{{ request.user.full_name }}</span>
                    <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400">{{ request.user.email }}</span>
                </div>
                <ul class="py-1" aria-labelledby="user-menu-button">
                    <li>
                        <a href="{% url 'user_profile:profile' %}"
                           class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Profile</a>
                    </li>
                    <li>
                        <a class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" type="button" data-modal-toggle="logout-modal">
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
            <button data-collapse-toggle="mobile-menu-2" type="button"
                    class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                    aria-controls="mobile-menu-2" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                          clip-rule="evenodd"></path>
                </svg>
            </button>
        </div>
        <div class="hidden justify-between items-center w-full md:flex md:w-auto md:order-1" id="mobile-menu-2">
            <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                    <a href="#"
                       class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
                       aria-current="page">Home</a>
                </li>
                <li>
                    <a href="{% url 'assistance:assistance-list' %}"
                       class="block py-2 pr-4 pl-3 text-gray-700

                               {% block activate_assistance_nav %}{% endblock activate_assistance_nav %} rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Assistance</a>
                </li>
                <li>
                    <a href="{% url 'petition:petition-list' %}"
                       class="block py-2 pr-4 pl-3 text-gray-700
                               {% block activate_petitions_nav %}{% endblock activate_petitions_nav %} rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Petitions</a>
                </li>
                <li>
                    <a href="{% url 'user:user-list' %}"
                       class="block py-2 pr-4 pl-3 text-gray-700
                               {% block activate_user_nav %}{% endblock activate_user_nav %} rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Volunteers</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% include 'modal/logout_modal.html' %}

<div class="container mx-auto">
    {% block content %}{% endblock %}
</div>

<script src="{% static "js/flowbite.js" %}"></script>
<script src="{% static "js/datepicker.js" %}"></script>
</body>
</html>

templates/paginator.html
<nav class="flex justify-between items-center pt-4" aria-label="Table navigation">
            <span class="text-sm font-normal text-gray-500 dark:text-gray-400">Showing <span
                    class="font-semibold text-gray-900 dark:text-white">{{ page_obj.start_index }}-{{ page_obj.end_index }}</span> of <span
                    class="font-semibold text-gray-900 dark:text-white">{{ paginator.count }}</span></span>
    <ul class="inline-flex items-center -space-x-px">
        {% if page_obj.has_previous %}
            <li>
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
                   class="block py-2 px-3 ml-0 leading-tight text-gray-500 bg-white rounded-l-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    <span class="sr-only">Previous</span>
                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                              clip-rule="evenodd"></path>
                    </svg>
                </a>
            </li>
        {% else %}
            <li>
                <a class="block py-2 px-3 ml-0 leading-tight text-gray-500 bg-white rounded-l-lg border border-gray-300">
                    <span class="sr-only">Previous</span>
                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                              clip-rule="evenodd"></path>
                    </svg>
                </a>
            </li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li>
                    <a aria-current="page"
                       class="z-10 py-2 px-3 leading-tight text-blue-600 bg-blue-50 border border-blue-300 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">{{ i }}</a>
                </li>
            {% else %}
                <li>
                    <a href="{{ request.path }}?page={{ i }}"
                       class="py-2 px-3 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li>
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"
                   class="block py-2 px-3 leading-tight text-gray-500 bg-white rounded-r-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    <span class="sr-only">Next</span>
                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                              clip-rule="evenodd"></path>
                    </svg>
                </a>
            </li>
        {% else %}
            <li>
                <a class="block py-2 px-3 leading-tight text-gray-500 bg-white rounded-r-lg border border-gray-300">
                    <span class="sr-only">Next</span>
                    <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                              clip-rule="evenodd"></path>
                    </svg>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>