api/urls.py
from django.urls import path

from api.views import AssistanceViewSet

app_name = "api"

urlpatterns = [
    path("assistance/", AssistanceViewSet.as_view({"get": "list"})),
    path("assistance/detail/<int:pk>/", AssistanceViewSet.as_view({"get": "retrieve"}))
]

assistance/urls.py
from django.urls import path

from assistance import views

app_name = "assistance"

urlpatterns = [
    path("", views.AssistanceListView.as_view(), name="assistance-list"),
    path("create/", views.AssistanceCreateView.as_view(), name="assistance-create"),
    path("detail/<int:pk>/", views.AssistanceDetailView.as_view(), name="assistance-detail"),
    path("update/<int:pk>/", views.AssistanceUpdateView.as_view(), name="assistance-update"),
    path("delete/<int:pk>/", views.AssistanceDeleteView.as_view(), name="assistance-delete")
]

follower/urls.py
from django.urls import path

from follower import views

app_name = "follower"

urlpatterns = [
    path("add/<int:pk>/", views.AddFollower.as_view(), name="follower-add"),
    path("remove/<int:pk>/", views.RemoveFollower.as_view(), name="follower-delete")
]

portal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from graphene_django.views import GraphQLView
from rest_framework_swagger.views import get_swagger_view

from api.schemas import schema
from portal import settings

schema_view = get_swagger_view(title='Volunteer portal API')

urlpatterns = [
    path('admin/', admin.site.urls),

    path("auth/", include("authentication.urls")),
    path("auth/", include("social_django.urls"), name="social"),
    path("profile/", include("user_profile.urls")),
    path("follower/", include("follower.urls")),
    path("user/", include("user.urls")),
    path("assitance/", include("assistance.urls")),
    path("petition/", include("petition.urls")),

    path("api/", include("api.urls")),
    path("swagger/", schema_view),

    path("graphql/", GraphQLView.as_view(graphiql=True, schema=schema)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from user import views

app_name = "user"

urlpatterns = [
    path("", views.UserListView.as_view(), name="user-list"),
    path("detail/<int:pk>/", views.UserDetailView.as_view(), name="user-detail")
]

user/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView

from assistance.models import Assistance
from authentication.models import User
from follower.models import Follower
from user.filters import UserFilter


class UserListView(LoginRequiredMixin, ListView):
    """Get list of user"""

    model = User
    paginate_by = 3
    template_name = "user/user_list.html"

    def get_queryset(self):
        queryset = self.model.objects.all()
        f = UserFilter(self.request.GET, queryset)
        return f.qs


class UserDetailView(LoginRequiredMixin, DetailView):
    """Get user data"""

    model = User
    template_name = "user/user_detail.html"
    context_object_name = "user"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = get_object_or_404(self.model, pk=self.kwargs["pk"])
        context["assistance"] = Assistance.objects.filter(user_id=self.kwargs["pk"])
        context["assistance_count"] = Assistance.objects.filter(user_id=self.kwargs["pk"]).count()
        context["follower_count"] = Follower.objects.filter(user_id=self.kwargs["pk"]).count()
        context["following_count"] = Follower.objects.filter(subscriber_id=self.kwargs["pk"]).count()
        context["is_following"] = Follower.objects.filter(
            subscriber=self.request.user,
            user_id=self.kwargs["pk"]
        )
        return context

templates/user/base.html
{% extends 'base.html' %}

{% block activate_user_nav %}text-blue-700{% endblock activate_user_nav %}

templates/user/user_detail.html
{% extends 'user/base.html' %}

{% block content %}
<div class="flex p-5">
    <div>
        <img class="w-36 h-36 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-5.jpg"
            alt="Rounded avatar" />
    </div>
    <div>
        <div class="flex items-center ml-6 mt-4">
            <div class="ml-1 mr-8">
                <h3 class="text-xl font-medium" style="text-transform: capitalize;">{{ user.first_name }} {{ user.last_name }}</h3>
            </div>
            <div class="ml-6 mr-0">
                {% if is_following %}
                <form method="post" action="{% url 'follower:follower-delete' user.id %}">
                    {% csrf_token %}
                    <button
                        class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-4 py-2 text-center mr-2">
                        Unfollow
                    </button>
                </form>
                {% else %}
                <form method="post" action="{% url 'follower:follower-add' user.id %}">
                    {% csrf_token %}
                    <button
                        class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-4 py-2 text-center mr-2">
                        Follow
                    </button>
                </form>
                {% endif %}
            </div>
        </div>
        <div class="flex ml-6 mt-4 text-sm">
            <div class="flex ml-1 mr-4">
                <p class="font-bold">{{ assistance_count }}</p>
                <p class="ml-1">assistance</p>
            </div>
            <div class="flex mr-4">
                <p class="font-bold">{{ follower_count }}</p>
                <p class="ml-1">followers</p>
            </div>
            <div class="flex">
                <p class="font-bold">{{ following_count }}</p>
                <p class="ml-1">following</p>
            </div>
        </div>
        <div class="ml-6 mt-4">
            <div style="width: 28rem;" class="ml-1">
                <p class="text-sm">{{ user.bio|default:"" }}</p>
            </div>
        </div>
    </div>
</div>
<div class="text-sm font-medium text-center text-gray-500 border-b border-gray-200">
    <ul class="flex justify-between">
        <li class="mr-2">
            <a class="inline-block p-3 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active">Assistance</a>
        </li>
        {% if user == request.user %}
        <li class="mr-2 flex items-center">
            <a href="{% url 'assistance:assistance-create' %}" class="inline-block text-blue-700 hover:text-white border border-blue-700 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-1.5 text-center">
                Add Assistance
            </a>
        </li>
        {% endif %}
    </ul>
</div>
<div class="mt-2 grid grid-cols-2 gap-2 pb-2">
    {% for item in assistance %}
    <div class="w-full bg-white rounded-lg border border-gray-200 shadow-md">
        <div class="flex justify-end px-4 pt-3 pb-2 relative">
            <button id="dropdownButton" data-dropdown-toggle="dropdown"
                class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg text-sm p-1.5"
                type="button">
                <span class="sr-only">Open dropdown</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z">
                    </path>
                </svg>
            </button>
            <!-- Dropdown menu -->
            <div id="dropdown"
                class="hidden z-10 w-44 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700">
                <ul class="py-1" aria-labelledby="dropdownButton">
                    {% if item.user == request.user %}
                    <li>
                        <a href="{% url 'assistance:assistance-update' item.id %}"
                            class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100">Edit</a>
                    </li>
                    <li>
                        <a href="{% url 'assistance:assistance-delete' item.id %}"
                            class="block py-2 px-4 text-sm text-red-600 hover:bg-gray-100">Delete</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="#"
                            class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100">Report</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <div class="w-f bg-white rounded-lg">
            <a href="{% url 'assistance:assistance-detail' item.id %}">
                <img class="px-5" src="https://flowbite.com/docs/images/blog/image-1.jpg" alt="" />
            </a>
            <div class="p-5">
                <a>
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ item.name }}</h5>
                </a>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
                    {{ item.description|truncatechars_html:110 }}
                </p>
                <a href="{{ item.payment_url }}" target="_blank"
                    class="inline-flex items-center focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2">
                    Donate
                </a>
                <a href="{% url 'assistance:assistance-detail' item.id %}" class="inline-flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 focus:outline-none">
                    Detail
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/user/user_list.html
{% extends 'user/base.html' %}

{% block title %}Volunteer | List{% endblock %}

{% block content %}
    <div class="overflow-x-auto p-3">
        <div class="flex justify-between items-center pb-4">
            <div>
                <button id="dropdownRadioButton" data-dropdown-toggle="dropdownRadio"
                        class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
                        type="button">
                    <svg class="mr-2 w-4 h-4 text-gray-400" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z"
                              clip-rule="evenodd"></path>
                    </svg>
                    Last 30 days
                    <svg class="ml-2 w-3 h-3" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                         xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                    </svg>
                </button>
                <!-- Dropdown menu -->
                <div id="dropdownRadio"
                     class="hidden z-10 w-48 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
                     data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom"
                     style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 10px);">
                    <ul class="p-3 space-y-1 text-sm text-gray-700 dark:text-gray-200"
                        aria-labelledby="dropdownRadioButton">
                        <li>
                            <div class="flex items-center p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-600">
                                <input id="filter-radio-example-1" type="radio" value="" name="filter-radio"
                                       class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                <label for="filter-radio-example-1"
                                       class="ml-2 w-full text-sm font-medium text-gray-900 rounded dark:text-gray-300">Last
                                    day</label>
                            </div>
                        </li>
                        <li>
                            <div class="flex items-center p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-600">
                                <input checked="" id="filter-radio-example-2" type="radio" value="" name="filter-radio"
                                       class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                <label for="filter-radio-example-2"
                                       class="ml-2 w-full text-sm font-medium text-gray-900 rounded dark:text-gray-300">Last
                                    7 days</label>
                            </div>
                        </li>
                        <li>
                            <div class="flex items-center p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-600">
                                <input id="filter-radio-example-3" type="radio" value="" name="filter-radio"
                                       class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                <label for="filter-radio-example-3"
                                       class="ml-2 w-full text-sm font-medium text-gray-900 rounded dark:text-gray-300">Last
                                    30 days</label>
                            </div>
                        </li>
                        <li>
                            <div class="flex items-center p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-600">
                                <input id="filter-radio-example-4" type="radio" value="" name="filter-radio"
                                       class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                <label for="filter-radio-example-4"
                                       class="ml-2 w-full text-sm font-medium text-gray-900 rounded dark:text-gray-300">Last
                                    month</label>
                            </div>
                        </li>
                        <li>
                            <div class="flex items-center p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-600">
                                <input id="filter-radio-example-5" type="radio" value="" name="filter-radio"
                                       class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                                <label for="filter-radio-example-5"
                                       class="ml-2 w-full text-sm font-medium text-gray-900 rounded dark:text-gray-300">Last
                                    year</label>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <form method="get">
                <label for="table-search" class="sr-only">Search</label>
                <div class="relative">
                    <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                        <svg class="w-5 h-5 text-gray-500 dark:text-gray-400" aria-hidden="true" fill="currentColor"
                             viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                  d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                                  clip-rule="evenodd"></path>
                        </svg>
                    </div>
                    <input type="text" id="table-search"
                           class="block p-2 pl-10 w-80 text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                           placeholder="Search for volunteer" name="first_name__icontains" value="{{ request.GET.first_name__icontains }}">
                </div>
            </form>
        </div>
        <table class="border w-full text-sm text-left text-gray-500">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="py-3 px-6">
                    User photo
                </th>
                <th scope="col" class="py-3 px-6">
                    Full name
                </th>
                <th scope="col" class="py-3 px-6">
                    Verified
                </th>
                <th scope="col" class="py-3 px-6">
                    Action
                </th>
            </tr>
            </thead>
            <tbody>
            {% for user in object_list %}
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                    <td class="py-4 px-6">
                        <img class="w-8 h-8 rounded-full" src="https://flowbite.com/docs/images/people/profile-picture-5.jpg" alt="Rounded avatar">
                    </td>
                    <th scope="row" style="text-transform: capitalize"
                        class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {{ user.full_name }}
                    </th>
                    <td class="py-4 px-6">
                        {% if user.is_verified is True %}
                            Yes
                        {% else %}
                            No
                        {% endif %}
                    </td>
                    <td class="py-4 px-6">
                        <a href="{% url 'user:user-detail' user.id %}"
                           class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Detail</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'paginator.html' %}
    </div>
{% endblock %}